### ISSUE TITLE
Colors: Hex-Value doesn't match color

### ISSUE THREAD

**Issue by remarcable** [barricadeio/styleguide#1]
"bon jour" suggests, that it is the background color. It is not, it's something that looks more brown. The actual color for bon jour is #f4f5f8, not #dfdfdf.

<img width="197" alt="screen shot 2015-11-17 at 12 22 14" src="https://cloud.githubusercontent.com/assets/11751444/11210092/e17bf5b8-8d25-11e5-9da6-dce7eefb266f.png">

**Comment by flynnduism** [comment]
Yep, that's an error in the color documentation. The hex value displayed for `$light1` (bon jour) was confused with the value for `$light3` (athens grey).

Thanks @lightningboss, we've [amended the page](https://github.com/barricadeio/styleguide/commit/99ad0a856e61556d1114dfffb440ed9fc3b51b9e) and are deploying the correction now.

**Comment by flynnduism** [comment]
Changes are [live](https://styleguide.barricade.io/styles.html). Thanks @lightningboss!
